In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn

In [37]:
df=pd.read_csv('scrapped_data.csv')
df

,Unnamed: 0,Product,Star_Rating,Ratings & Reviews,Offer_price,Market_Price,Discount
0,3,"realme 9i (Prism Blue, 128 GB)",4.5,"84,095 Ratings & 4,630 Reviews","₹11,099","₹16,999",34% off
1,4,"realme 9i (Prism Black, 128 GB)",4.5,"84,095 Ratings & 4,630 Reviews","₹11,099","₹16,999",34% off
2,5,"realme C31 (Dark Green, 32 GB)",4.6,"36,498 Ratings & 1,375 Reviews","₹9,299","₹10,999",15% off
3,6,GREENBERRI F1,3.9,"1,224 Ratings & 88 Reviews","₹1,399","₹1,499",6% off
4,7,"realme C31 (Dark Green, 64 GB)",4.4,"35,514 Ratings & 1,799 Reviews","₹9,999","₹11,999",16% off
...,...,...,...,...,...,...,...
648,1134,Itel it2163S,4.0,238 Ratings & 25 Reviews,₹999,NaN,NaN
649,1136,"MOTOROLA Edge 20 5G (Frosted Onyx, 128 GB)",4.1,"8,649 Ratings & 1,279 Reviews","₹27,999","₹34,999",20% off
650,1139,"realme C21 (Cross Blue, 32 GB)",4.4,"71,122 Ratings & 3,892 Reviews","₹9,999",NaN,NaN
651,1140,Salora Coral,3.8,438 Ratings & 45 Reviews,₹899,NaN,NaN
652,1141,"SAMSUNG Galaxy A12 (Black, 128 GB)",4.1,"1,212 Ratings & 93 Reviews","₹14,970","₹15,490",3% off

In [38]:
#dropping first column
df.drop(columns=['Unnamed: 0'],inplace=True)

In [40]:
df.drop_duplicates(keep = 'first' , inplace= True)

# data cleaning

In [41]:
df.head()

,Product,Star_Rating,Ratings & Reviews,Offer_price,Market_Price,Discount
0,"realme 9i (Prism Blue, 128 GB)",4.5,"84,095 Ratings & 4,630 Reviews","₹11,099","₹16,999",34% off
1,"realme 9i (Prism Black, 128 GB)",4.5,"84,095 Ratings & 4,630 Reviews","₹11,099","₹16,999",34% off
2,"realme C31 (Dark Green, 32 GB)",4.6,"36,498 Ratings & 1,375 Reviews","₹9,299","₹10,999",15% off
3,GREENBERRI F1,3.9,"1,224 Ratings & 88 Reviews","₹1,399","₹1,499",6% off
4,"realme C31 (Dark Green, 64 GB)",4.4,"35,514 Ratings & 1,799 Reviews","₹9,999","₹11,999",16% off

In [42]:
# removing nulls
df.dropna(how='all' ,thresh = 2, inplace= True  )

In [43]:
df.shape

(641, 6)

In [46]:
df.to_csv("raw_data_1.csv")